# Generated by Django 4.2.16 on 2025-01-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_address_author_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='book',
            name='country_publised',
            field=models.ManyToManyField(to='book_outlet.country'),
        ),
    ]
